translate:
  projectId: "banca-355515"
  activityType:
    activityType: ["Attività di Processo", "Attività di Controllo", "Attività di Processo Comune", "Attività di Sistema"]
    activityTypeEnglish: ["process activity", "control activity", "common process activity", "system activity"]
  activityCategory:
    activityCategory: ["Professionale", "Operativa", "Commerciale"]
    activityCategoryEnglish: ["Professional", "Operational", "Commercial"]
  actorType:
    actorType: ["Unità organizzativa", "Posizione", "Persona", "Gruppo Vuoto", "Unità organizzativa esterna"]
    actorTypeEnglish: ["Organizational unit", "Position", "Person", "NA", "External Organizational unit"]
  controlType:
    controlType: ['Manuale', 'vuoto', 'Semiautomatico', 'Automatico', 'N.A.']
    controlTypeEnglish: ['Manual', 'NA', 'Semi-automatic', 'Automatic', 'NA']
  controlPeriodocity:
    controlPeriodocity: ['Ad evento', 'vuoto', 'Trimestrale', 'Semestrale', 'Annua', 'Mensile', 'Settimanale', 'Giornaliera', 'Decadale', 'N.A.']
    controlPeriodocityEnglish: ['Per event', 'NA', 'Quarterly', 'Half yearly', 'Annually', 'Monthly', 'Weekly', 'Daily', 'Decadal', 'NA']
  riskType:
    riskType: ['Altri rischi (operativi)', 'Rischio di Informativa Finanziaria (ex 262/2005)', 'Legale e di non Conformità', 'N.A.', 'Rischio Information and Communication Technology']
    riskTypeEnglish: ['Other risks (operational)', 'Financial Information Risk (ex 262/2005)', 'Legal and non-compliance', 'NA', 'Information and Communication Technology risk']
